### ISSUE TITLE
Block comments after macro definition may have wrong highlighting

### ISSUE THREAD

**Issue by asesidaa** [babyraging/yash#11]
If there is a block comment after macro definition and have multiple lines, the syntax highlighting may go wrong

![Snipaste_2021-02-25_00-58-55](https://user-images.githubusercontent.com/26689773/109038540-cabfab00-7706-11eb-83ba-ff0d8296d9d1.png)

Test code:

``` bison
/**
Test
*/

%{
    /*This
    works fine
    */
    #include <iostream>
    
    #define TEST 1 /*This also works*/
    #define PROBLEM 2 /*This
    will cause false highlighting*/
    
    %}
```

**Comment by babyraging** [comment]
Hi there, thank you for the issue!

I think this is a C++ syntax highlighter's problem, since we are handling whatever code inside the {% %} brackets to the C++ highlighter. 

In fact, I've tried to use your snippet code (without the {% %} brackets) with C++ as selected language, VSCode gives syntax error.

![image](https://user-images.githubusercontent.com/14004642/109060059-3bee6680-76e5-11eb-9e16-4d228ae6a078.png)

**Comment by asesidaa** [comment]
It seems to be an existing issue that has not been fixed https://github.com/jeff-hykin/cpp-textmate-grammar/issues/527
