### ISSUE TITLE
add undefined non-terminals/terminals in yacc files to autocomplete

### ISSUE THREAD

**Issue by srinathgs** [babyraging/yash#15]
Hi,
Hope you're doing well. I have been writing a lot of yacc of late, I found a minor niggle that would enhance this extension by a great extent. 

I have seen this with other extensions where, unrecognised/undefined variables appear in intellisense with `abc` prefix as shown in screenshot. It even autocompletes such variable names across all open files in different languages. 
![Screenshot from 2021-05-15 12-35-16](https://user-images.githubusercontent.com/1170493/118351757-5f55de80-b57b-11eb-81a8-0cff796c4884.png)

But, with Yash, only defined tokens and non-terminals appear in intellisense. As I have been writing a lot of yacc production rules of late, what I observed is we first write a non-terminal production rule followed by other non-terminals used in the previous non-terminal production rule and so on till we reach a terminal/token. In other words, you can say that we do this definition in a top down fashion. 

In such a case, it is easy to misspell non-terminals used in multiple places before we get to actually define the non-terminal in question. Hence, by autocompleting words in the same yacc file under the `abc` category as shown in the screenshot would save a lot of time and reduces room for error. 

Hope this gets considered and adds to the already amazing Yash extension.

Thanks!
Srinath

**Comment by babyraging** [comment]
Hi Srinath!

That sounds a good idea! I don't know why VSCode doesn't have that as a fallback intellisense already.

I've looked around a bit and I'm afraid that there is not a "pre-built" solution to it, we have to do it on our own. It isn't actually a big deal, since we're already parsing the entire file, we just need to save the words some where.

Can you please check if the other official languages extensions have also `abc` type in? In this way we can check how they did it. I've checked the Typescript one and it seems like it suggests only words that have semantic meanings, just like ours. 

Either way, I think this can be certainly added to the extension.

**Comment by srinathgs** [comment]
I found that the [ragel extension](https://github.com/RReverser/vsce-ragel) supports it. The screenshot I took was from it. I have noticed that [Go extension](https://github.com/golang/vscode-go) supports it too. Not sure if these qualify as official language extensions.

Hope it helps!

**Comment by srinathgs** [comment]
I observed that in the token section, this works in yash too.

**Comment by babyraging** [comment]
@srinathgs 

Hi! Sorry for the super super long wait, I'm actually embarrassed, I just didn't have much time.

This is what I did, I hope it suffices the requirement.

If there is any completion it shows it.
![image](https://user-images.githubusercontent.com/14004642/147248675-490dd62e-16c9-4b6a-8643-4b81d8778396.png)

If there is not, it falls back to the standard abc.
![image](https://user-images.githubusercontent.com/14004642/147248782-d572cd00-8480-4aa1-8338-3d37e3abd37a.png)
