### ISSUE TITLE
Highlighting bug on %union

### ISSUE THREAD

**Issue by marzojr** [babyraging/yash#4]
Whenever there is a template variable defined inside a %union in a Bison/Yacc file, the token in the next line does not get colorized.

Minimal repro:

```
%union {
	class std::vector<int> *varvec;
	int intval;
}
```
In this example, 'int' is not colorized.

**Comment by babyraging** [comment]
Hi there, thanks for the issue.

The syntax highlight inside the %union block is handled by the default C/C++ highlighter, therefore if there is a bug, we cannot do anything about it.

In this particular case, you will also find that the entire second line will not be highlighted, if you try to write those 2 lines of code inside a .cpp file. 

I think this might be a bug for the C/C++ highlighter since the syntax is good according to the compiler. 
Anyway, in C++ you don't need to write "class", `std::vector<int>* varvec;` is already good :), in this everything gets colorized.

**Comment by babyraging** [comment]
Closing the issue since we cannot do anything about it.
